<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/lacms_operational_helpers.php';
requireLacmsPermission('lacms.meetings.view');
$pdo=db();$id=(int)($_GET['id']??0);
$q=$pdo->prepare("SELECT m.*,e.event_reference,a.agenda_reference,c.name committee_name,cu.full_name chair_name,su.full_name secretary_name FROM lacms_meetings m LEFT JOIN lacms_calendar_events e ON e.id=m.calendar_event_id LEFT JOIN lacms_agendas a ON a.id=m.agenda_id LEFT JOIN committees c ON c.id=m.committee_id LEFT JOIN users cu ON cu.id=m.chair_user_id LEFT JOIN users su ON su.id=m.secretary_user_id WHERE m.id=:id");$q->execute([':id'=>$id]);$m=$q->fetch();if(!$m)exit('Meeting not found.');
$p=$pdo->prepare("SELECT p.*,u.full_name,u.email FROM lacms_meeting_participants p LEFT JOIN users u ON u.id=p.user_id WHERE p.meeting_id=:id ORDER BY p.id");$p->execute([':id'=>$id]);$participants=$p->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><title><?= e($m['meeting_reference']) ?></title><style>body{font:12px Arial;margin:28px;color:#111827}.head{text-align:center;border-bottom:3px solid #0f2137;padding-bottom:12px;margin-bottom:15px}.box{border:1px solid #ccc;padding:9px;margin:8px 0}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ccc;padding:6px;vertical-align:top}th{background:#eee}</style></head><body onload="window.print()"><div class="head"><strong><?= e(APP_NAME) ?></strong><h2>Meeting Coordination Record</h2><div><?= e($m['meeting_reference']) ?></div></div><h3><?= e($m['title']) ?></h3><div class="box"><strong>Type:</strong> <?= e($m['meeting_type']) ?><br><strong>Schedule:</strong> <?= formatDateTime($m['start_datetime']) ?><?= $m['end_datetime']?' to '.formatDateTime($m['end_datetime']):'' ?><br><strong>Venue:</strong> <?= e($m['venue']?:'TBA') ?><br><strong>Calendar:</strong> <?= e($m['event_reference']?:'—') ?><br><strong>Agenda:</strong> <?= e($m['agenda_reference']?:'—') ?><br><strong>Committee:</strong> <?= e($m['committee_name']?:'—') ?><br><strong>Chair:</strong> <?= e($m['chair_name']?:'—') ?><br><strong>Secretary:</strong> <?= e($m['secretary_name']?:'—') ?><br><strong>Status:</strong> <?= e($m['status']) ?><?php if($m['purpose']): ?><br><br><strong>Purpose:</strong><br><?= nl2br(e($m['purpose'])) ?><?php endif; ?></div><h3>Participants</h3><table><thead><tr><th>Name</th><th>Role</th><th>Response</th><th>Attendance</th><th>Required</th></tr></thead><tbody><?php foreach($participants as $x): ?><tr><td><?= e($x['full_name']?:$x['external_name']?:'—') ?></td><td><?= e($x['participant_role']) ?></td><td><?= e($x['response_status']) ?></td><td><?= e($x['attendance_status']) ?></td><td><?= $x['attendance_required']?'Yes':'No' ?></td></tr><?php endforeach; ?></tbody></table></body></html>
