<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/lacms_sync_helpers.php';
requireLacmsPermission('lacms.sync.manage');
if($_SERVER['REQUEST_METHOD']!=='POST')jsonResponse(false,'Invalid request method.');requireCsrf();
$pdo=db();$syncId=(int)($_POST['sync_record_id']??0);$actionId=(int)($_POST['action_id']??0);$mode=clean($_POST['mode']??'save');
$sync=lacmsSyncContext($pdo,$syncId);if(!$sync)jsonResponse(false,'Coordination record not found.');if(in_array($sync['status'],['Closed','Cancelled'],true))jsonResponse(false,'Closed coordination records cannot be changed.');
if($mode==='delete'){$q=$pdo->prepare('SELECT * FROM lacms_sync_actions WHERE id=:id AND sync_record_id=:sync');$q->execute([':id'=>$actionId,':sync'=>$syncId]);$old=$q->fetch();if(!$old)jsonResponse(false,'Action not found.');$pdo->prepare('DELETE FROM lacms_sync_actions WHERE id=:id')->execute([':id'=>$actionId]);lacmsSyncHistory($pdo,$syncId,'Remove Action',$sync['status'],$sync['status'],'Removed coordination action: '.$old['action_title'].'.');jsonResponse(true,'Action removed.');}
$title=clean($_POST['action_title']??'');$desc=trim((string)($_POST['action_description']??''));$user=(int)($_POST['responsible_user_id']??0)?:null;$office=(int)($_POST['responsible_office_id']??0)?:null;$due=clean($_POST['due_datetime']??'')?:null;$priority=clean($_POST['priority_level']??'Normal');$status=clean($_POST['status']??'Pending');$notes=trim((string)($_POST['completion_notes']??''));
if($title==='')jsonResponse(false,'Action title is required.');if(!in_array($priority,['Low','Normal','High','Urgent'],true)||!in_array($status,lacmsSyncActionStatuses(),true))jsonResponse(false,'Invalid action settings.');
try{
 if($actionId){$q=$pdo->prepare('SELECT * FROM lacms_sync_actions WHERE id=:id AND sync_record_id=:sync');$q->execute([':id'=>$actionId,':sync'=>$syncId]);$old=$q->fetch();if(!$old)jsonResponse(false,'Action not found.');$pdo->prepare('UPDATE lacms_sync_actions SET action_title=:title,action_description=:description,responsible_user_id=:user,responsible_office_id=:office,due_datetime=:due,priority_level=:priority,status=:status,completion_notes=:notes,completed_by=CASE WHEN :completed_flag=1 THEN :completed_user ELSE NULL END,completed_at=CASE WHEN :completed_time=1 THEN COALESCE(completed_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE id=:id')->execute([':title'=>$title,':description'=>$desc?:null,':user'=>$user,':office'=>$office,':due'=>$due,':priority'=>$priority,':status'=>$status,':notes'=>$notes?:null,':completed_flag'=>$status==='Completed'?1:0,':completed_user'=>currentUserId(),':completed_time'=>$status==='Completed'?1:0,':id'=>$actionId]);$message='Coordination action updated.';}
 else{$pdo->prepare('INSERT INTO lacms_sync_actions (sync_record_id,action_title,action_description,responsible_user_id,responsible_office_id,due_datetime,priority_level,status,completion_notes,completed_by,completed_at,created_by,created_at,updated_at) VALUES(:sync,:title,:description,:user,:office,:due,:priority,:status,:notes,:completed_by,:completed_at,:created,NOW(),NOW())')->execute([':sync'=>$syncId,':title'=>$title,':description'=>$desc?:null,':user'=>$user,':office'=>$office,':due'=>$due,':priority'=>$priority,':status'=>$status,':notes'=>$notes?:null,':completed_by'=>$status==='Completed'?currentUserId():null,':completed_at'=>$status==='Completed'?date('Y-m-d H:i:s'):null,':created'=>currentUserId()]);$actionId=(int)$pdo->lastInsertId();$message='Coordination action added.';}
 lacmsSyncHistory($pdo,$syncId,'Action',$sync['status'],$sync['status'],$message.' '.$title);lacmsAudit('Action','LACMS Sync Action',(string)$actionId,null,['sync_record_id'=>$syncId,'title'=>$title,'status'=>$status]);jsonResponse(true,$message,['id'=>$actionId]);
}catch(Throwable $e){jsonResponse(false,APP_DEBUG?$e->getMessage():'Unable to save coordination action.');}
