<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/lacms_operational_helpers.php';
requireLacmsPermission('lacms.calendar.view');
$pdo=db();$id=(int)($_GET['id']??0);
$q=$pdo->prepare("SELECT e.*,a.agenda_reference,c.name committee_name,o.name office_name FROM lacms_calendar_events e LEFT JOIN lacms_agendas a ON a.id=e.agenda_id LEFT JOIN committees c ON c.id=e.committee_id LEFT JOIN offices o ON o.id=e.office_id WHERE e.id=:id");$q->execute([':id'=>$id]);$e=$q->fetch();if(!$e)exit('Event not found.');
$p=$pdo->prepare("SELECT p.*,u.full_name,u.email FROM lacms_calendar_event_participants p LEFT JOIN users u ON u.id=p.user_id WHERE p.calendar_event_id=:id ORDER BY p.id");$p->execute([':id'=>$id]);$participants=$p->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><title><?= e($e['event_reference']) ?></title><style>body{font:12px Arial;margin:28px;color:#111827}.head{text-align:center;border-bottom:3px solid #0f2137;padding-bottom:12px;margin-bottom:15px}.box{border:1px solid #ccc;padding:9px;margin:8px 0}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ccc;padding:6px;vertical-align:top}th{background:#eee}</style></head><body onload="window.print()"><div class="head"><strong><?= e(APP_NAME) ?></strong><h2>Legislative Calendar Activity</h2><div><?= e($e['event_reference']) ?></div></div><h3><?= e($e['title']) ?></h3><div class="box"><strong>Type:</strong> <?= e($e['event_type']) ?><br><strong>Schedule:</strong> <?= formatDateTime($e['start_datetime']) ?><?= $e['end_datetime']?' to '.formatDateTime($e['end_datetime']):'' ?><br><strong>Venue:</strong> <?= e($e['venue']?:'TBA') ?><br><strong>Agenda:</strong> <?= e($e['agenda_reference']?:'—') ?><br><strong>Committee:</strong> <?= e($e['committee_name']?:'—') ?><br><strong>Status:</strong> <?= e($e['status']) ?><br><strong>Conflict Status:</strong> <?= e($e['conflict_status']) ?></div><h3>Participants</h3><table><thead><tr><th>Name</th><th>Role</th><th>Response</th><th>Required</th></tr></thead><tbody><?php foreach($participants as $x): ?><tr><td><?= e($x['full_name']?:$x['external_name']?:'—') ?></td><td><?= e($x['participant_role']) ?></td><td><?= e($x['response_status']) ?></td><td><?= $x['attendance_required']?'Yes':'No' ?></td></tr><?php endforeach; ?></tbody></table></body></html>
