<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/lacms_operational_helpers.php';
requireLacmsPermission('lacms.agendas.view');

$pdo=db();$id=(int)($_GET['id']??0);
$q=$pdo->prepare("SELECT a.*,c.name committee_name,o.name office_name FROM lacms_agendas a LEFT JOIN committees c ON c.id=a.committee_id LEFT JOIN offices o ON o.id=a.office_id WHERE a.id=:id");$q->execute([':id'=>$id]);$a=$q->fetch();if(!$a)exit('Agenda not found.');
$i=$pdo->prepare("SELECT i.*,li.reference_number,su.full_name sponsor_name,pu.full_name presenter_name FROM lacms_agenda_items i LEFT JOIN legislative_items li ON li.id=i.legislative_item_id LEFT JOIN users su ON su.id=i.sponsor_user_id LEFT JOIN users pu ON pu.id=i.presenter_user_id WHERE i.agenda_id=:id AND i.item_status<>'Removed' ORDER BY i.sequence_number,i.id");$i->execute([':id'=>$id]);$items=$i->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><title><?= e($a['agenda_reference']) ?></title><style>body{font:12px Arial;margin:28px;color:#111827}.head{text-align:center;border-bottom:3px solid #0f2137;padding-bottom:12px;margin-bottom:15px}.box{border:1px solid #ccc;padding:9px;margin:8px 0}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ccc;padding:6px;vertical-align:top}th{background:#eee}</style></head><body onload="window.print()"><div class="head"><strong><?= e(APP_NAME) ?></strong><h2>Legislative Agenda</h2><div><?= e($a['agenda_reference']) ?></div></div><h3><?= e($a['title']) ?></h3><p><?= e($a['agenda_type']) ?> · <?= e($a['committee_name']?:'No committee') ?> · <?= $a['agenda_date']?formatDate($a['agenda_date']):'Unscheduled' ?> <?= $a['start_time']?formatTime($a['start_time']):'' ?></p><div class="box"><strong>Venue:</strong> <?= e($a['venue']?:'TBA') ?><br><strong>Status:</strong> <?= e($a['status']) ?><?php if($a['description']): ?><br><br><?= nl2br(e($a['description'])) ?><?php endif; ?></div><table><thead><tr><th>#</th><th>Section</th><th>Agenda Item</th><th>Legislative Ref.</th><th>Sponsor / Presenter</th><th>Priority</th><th>Status</th></tr></thead><tbody><?php foreach($items as $x): ?><tr><td><?= (int)$x['sequence_number'] ?></td><td><?= e($x['agenda_section']) ?></td><td><strong><?= e($x['title']) ?></strong><br><?= e($x['description']?:'') ?></td><td><?= e($x['reference_number']?:'—') ?></td><td><?= e(($x['sponsor_name']?:'').($x['presenter_name']?' / '.$x['presenter_name']:'')) ?></td><td><?= e($x['priority_level']) ?></td><td><?= e($x['item_status']) ?></td></tr><?php endforeach; ?></tbody></table></body></html>
